<?php

// Plugin definition
$plugin = array(
  'title' => t('CETAV  prev-cursos-libres'),
  'category' => t('CETAV'),
  'icon' => 'cetav_prev-cursos-libres.png',
  'theme' => 'cetav_prev-cursos-libres',
  'css' => 'cetav_prev-cursos-libres.css',
  'regions' => array(
    'left' => t('Left side'),
    'right' => t('Right side'),
    'wide' => t('Wide'),
    'wide_second' => t('Wide second')
  ),
);
