<?php

// Plugin definition
$plugin = array(
  'title' => t('CETAV empleabilidad'),
  'category' => t('CETAV'),
  'icon' => 'cetav_empleabilidad.png',
  'theme' => 'cetav_empleabilidad',
  'css' => 'cetav_empleabilidad.css',

  'regions' => array(
    'top' => t('Top'),
    'wide_first' => t('Wide first'),
    'left' => t('Left'),
    'right' => t('Right'),
    'wide_second' => t('Wide second'),
    'buttom' => t('Buttom'),

  ),
);
