<?php

// Plugin definition
$plugin = array(
  'title' => t('CETAV carreras'),
  'category' => t('CETAV'),
  'icon' => 'cetav_carreras.png',
  'theme' => 'cetav_carreras',
  'css' => 'cetav_carreras.css',

  'regions' => array(
    'wide' => t('Wide'),
    'left' => t('Left side'),
    'right' => t('Right side'),
    'wide_second' => t('Wide second'),
    'left_second' => t('Left side'),
    'right_second' => t('Right side'),
    'wide_third' => t('Wide third'),
  ),
);
