<?php

// Plugin definition
$plugin = array(
  'title' => t('CETAV  cursos libres'),
  'category' => t('CETAV'),
  'icon' => 'cetav_cursos_libres.png',
  'theme' => 'cetav_cursos_libres',
  'css' => 'cetav_cursos_libres.css',

  'regions' => array(
    'left' => t('Left side'),
    'right' => t('Right side'),
    'wide' => t('Wide'),
    'left_second' => t('Left side'),
    'right_second' => t('Right side'),
    'wide_second' => t('Wide second'),

  ),
);
