<?php

// Plugin definition
$plugin = array(
  'title' => t('CETAV  institucion'),
  'category' => t('CETAV'),
  'icon' => 'cetav_institucion.png',
  'theme' => 'cetav_institucion',
  'css' => 'cetav_institucion.css',

  'regions' => array(
    'wide_main' => t('Wide main'),
    'left' => t('Left side'),
    'right' => t('Right side'),
    'wide_intro' => t('Wide Intro'),
    'wide' => t('Wide'),
    'left_second' => t('Left side'),
    'right_second' => t('Right side'),
    'wide_second' => t('Wide second')
  ),
);
