<?php

// Plugin definition
$plugin = array(
  'title' => t('CETAV Egresados'),
  'category' => t('CETAV'),
  'icon' => 'cetav_egresados.png',
  'theme' => 'cetav_egresados',
  'css' => 'cetav_egresados.css',

  'regions' => array(
    'top' => t('Top'),
    'wide_first' => t('Wide First'),
    'wide_second' => t('Wide Second'),
    'wide_third' => t('Wide Third'),
    'bottom' => t('Botton'),

  ),
);
