<?php

// Plugin definition
$plugin = array(
  'title' => t('CETAV  admision'),
  'category' => t('CETAV'),
  'icon' => 'cetav_admision.png',
  'theme' => 'cetav_admision',
  'css' => 'cetav_admision.css',
  'regions' => array(
    'wide' => t('Wide'),
    'left' => t('Left side'),
    'right' => t('Right side'),
    'left_second' => t('Left side'),
    'right_second' => t('Right side'),
    'wide_second' => t('Wide'),
  ),
);
