<?php
/**
 * @file
 * Code for the Configuración feature.
 */

include_once 'configuracion_cetav.features.inc';


/**
 * Implements hook_form_FORM_ID_alter().
 */
function configuracion_cetav_form_user_profile_form_alter(&$form, &$form_alter){
  global $user;
  if (!in_array('egresado', $form['#user']->roles) && $form['#user']->uid == $user->uid) {
    unset($form['field_perfil_de_egresado']);
  }
}